# fly.toml app configuration file generated for fastify-app-weathered-night-642 on 2025-07-31T17:46:46+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fastify-app-weathered-night-642'
primary_region = 'jnb'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Enable fly.io to pull our custom metrics into its monitoring solution
[metrics]
  port = 9001
  path = '/metrics'
